#!/bin/sh

xmessage -buttons reboot,suspend,poweroff "$@" ""

case "$?" in
	101)
		/usr/bin/systemctl reboot
		;;
	102)
		/usr/bin/systemctl suspend
		;;
	103)
		/usr/bin/systemctl poweroff
		;;
esac
